---
- hosts: Danforth_Shakoor
  gather_facts: False
  remote_user: pi
  ignore_errors: True
  vars:
    img_dir: /home/pi/Images
    local_dir: /home/clizarraga/Raspberry_Pi/Images

  tasks:
    - name: Get local date Y-m-d
      local_action:
        shell date +%Y-%m-%d
      register: date
      delegate_to: clizarraga_chronos
      run_once: true

    - debug:
        msg: "Date variable is {{ date }} and stdout is {{ date.stdout }}"
      
    - name: Increase transmit power before file sending
      # local_action:
      #   shell rsh -l pi "{{ inventory_hostname }}" "sudo iwconfig wlan0 txpower 20 && echo Success"
      shell: iwconfig wlan0 txpower 20 && echo Success
      register: command_result
      become: yes
      changed_when: "'Success' in command_result.stdout"
      
    - name: Get file name(s)
      # local_action:
      #   shell rsh -l pi "{{ inventory_hostname }}" "(cd {{ img_dir }}; find . -maxdepth 1 -type f) | cut -d '/' -f2 && (echo Success >&2)"
      shell: "(cd {{ img_dir }} && find . -maxdepth 1 -type f) | cut -d '/' -f2 && (echo Success >&2)"
      register: files_to_copy
      changed_when: "'Success' in files_to_copy.stderr"

    - debug:
        msg: "Files_to_copy are {{ files_to_copy.stdout_lines }} and their length is {{ files_to_copy.stdout_lines | length }} and the comparison is {{ files_to_copy.stdout_lines | length | int >=1 }}"

    - name: Pull with rsh/ssh and rsync from chronos
      synchronize:
        src: "{{ img_dir }}/{{ item }}"
        dest: "{{ local_dir }}/{{ date.stdout }}/"
        mode: pull
        use_ssh_args: yes
        ssh_args: yes
        rsync_opts:
          # - "--rsh=rsh"
          - "--remove-source-files"
          - "--timeout=30"

      when: files_to_copy['stdout_lines'] | length | int >= 1
      with_items:
        "{{ files_to_copy.stdout_lines }}"

    - name: Decrease transmit power after sending file
      # local_action:
      #   shell rsh -l pi "{{ inventory_hostname }}" "sudo iwconfig wlan0 txpower 18 && echo Success"
      shell: iwconfig wlan0 txpower 18 && echo Success
      become: yes
      changed_when: "'Success' in command_result.stdout"
      